{
 "title": "389-ds-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(ds_scrape_success{job=\"$job\"},instance)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(ds_ldbm_instance_maxdncachesize{job=\"$job\", instance=\"$node\"},database)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of established connections",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ds_server_currentconnections{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "Established"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "description": "Current number of established connections",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ds_server_currentconnections{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Current number of active threads used for handling requests",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ds_server_threads{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backends",
   "type": "stat",
   "description": "Number of back ends (databases) the server services",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ds_server_nbackends{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time elapsed since the server directory was started",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ds_server_currenttime{job=\"$job\", instance=\"$node\"} - ds_server_starttime{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Binds",
   "type": "timeseries",
   "description": "Number of bind operations split by bind type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rate(ds_snmp_server_strongauthbinds{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Strong auth"
    },
    {
     "expr": "rate(ds_snmp_server_simpleauthbinds{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Simple auth"
    },
    {
     "expr": "rate(ds_snmp_server_unauthbinds{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Unauth"
    },
    {
     "expr": "rate(ds_snmp_server_anonymousbinds{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Anonymous"
    }
   ]
  },
  {
   "title": "Server operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDAP operations rate",
     "type": "timeseries",
     "description": "Averate number of operations per second executed by server",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(ds_server_opscompleted{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Completed"
      },
      {
       "expr": "rate(ds_server_opsinitiated{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Initiated"
      }
     ]
    },
    {
     "title": "LDAP requests rate",
     "type": "timeseries",
     "description": "Average number of operations per second performed by the server per second, split by operation type",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "rate(ds_snmp_server_searchops{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Search"
      },
      {
       "expr": "rate(ds_snmp_server_modifyentryops{job=\"$job\",instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Modify"
      },
      {
       "expr": "rate(ds_snmp_server_addentryops{job=\"$job\",instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Add"
      },
      {
       "expr": "rate(ds_snmp_server_removeentryops{job=\"$job\",instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Remove"
      },
      {
       "expr": "rate(ds_snmp_server_modifyrdnops{job=\"$job\",instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Modify RDN"
      }
     ]
    },
    {
     "title": "Entries sent rate",
     "type": "timeseries",
     "description": "Average number of records per second sent by the server to clients",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(ds_server_entriessent{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Read wiaters",
     "type": "timeseries",
     "description": "Connections with some requests waiting, not currently served by a server thread",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "ds_server_readwaiters{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Data sent rate",
     "type": "timeseries",
     "description": "Average amount of data sent by the server per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ds_server_bytessent{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Bytes"
      }
     ]
    },
    {
     "title": "Errors rate",
     "type": "timeseries",
     "description": "Average number of returned security-related errors, such as wrong passwords, invalid authentication methods, or higher security requirements",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(ds_snmp_server_errors{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Errors"
      },
      {
       "expr": "rate(ds_snmp_server_securityerrors{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Security errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Normalized DN cache size",
     "type": "timeseries",
     "description": "Available and used cache sizes of normalized DNs",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ds_ldbm_maxnormalizeddncachesize{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "ds_ldbm_currentnormalizeddncachesize{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Normalized DN cache tries/hits rate",
     "type": "timeseries",
     "description": "Number of normalized DN cache lookups per second",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "rate(ds_ldbm_normalizeddncachetries{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tries"
      },
      {
       "expr": "rate(ds_ldbm_normalizeddncachehits{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Hits"
      }
     ]
    },
    {
     "title": "Normalized DN cache efficiency",
     "type": "timeseries",
     "description": "Cache hit ratio",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ds_ldbm_normalizeddncachehitratio{job=\"$job\",instance=\"$node\"}",
       "legendFormat": "Hit ratio"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend caches - $database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "database",
   "collapsed": true,
   "panels": [
    {
     "title": "Entry cache size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ds_ldbm_instance_maxdncachesize{job=\"$job\", instance=\"$node\", database=\"$database\"}",
       "legendFormat": "total"
      },
      {
       "expr": "ds_ldbm_instance_currentdncachesize{job=\"$job\", instance=\"$node\", database=\"$database\"}",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "Entry cache tries/hits rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "targets": [
      {
       "expr": "rate(ds_ldbm_instance_entrycachetries{job=\"$job\", database=\"$database\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "tries"
      },
      {
       "expr": "rate(ds_ldbm_instance_entrycachehits{job=\"$job\", database=\"$database\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "hits"
      }
     ]
    },
    {
     "title": "DN cache hit ratio (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ds_ldbm_instance_dncachehitratio{job=\"$job\", database=\"$database\", instance=\"$node\"}",
       "legendFormat": "hit ratio"
      }
     ]
    },
    {
     "title": "DN cache size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ds_ldbm_instance_maxdncachesize{job=\"$job\", database=\"$database\", instance=\"$node\"}",
       "legendFormat": "total"
      },
      {
       "expr": "ds_ldbm_instance_currentdncachesize{job=\"$job\", database=\"$database\", instance=\"$node\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "DN cache tries/hits rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "expr": "rate(ds_ldbm_instance_dncachetries{job=\"$job\", database=\"$database\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "tries"
      },
      {
       "expr": "rate(ds_ldbm_instance_dncachehits{job=\"$job\", database=\"$database\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "hits"
      }
     ]
    },
    {
     "title": "Entry cache hit ratio (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ds_ldbm_instance_entrycachehitratio{job=\"$job\", database=\"$database\", instance=\"$node\"}",
       "legendFormat": "hit ratio"
      }
     ]
    }
   ]
  },
  {
   "title": "Berkeley DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB cache size",
     "type": "timeseries",
     "description": "Available and used DB cache sizes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ds_bdb_cache_size_bytes{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "ds_bdb_pages_in_use{job=\"$job\", instance=\"$node\"} * 4096",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "DB cache efficiency",
     "type": "timeseries",
     "description": "Cache hit ratio",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ds_bdb_dbcachehitratio{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Hit ratio"
      }
     ]
    },
    {
     "title": "DB cache hits/tries rate",
     "type": "timeseries",
     "description": "Number of DB cache lookups per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(ds_bdb_dbcachetries{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tries"
      },
      {
       "expr": "rate(ds_bdb_dbcachehits{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Hits"
      }
     ]
    },
    {
     "title": "DB cache pages",
     "type": "timeseries",
     "description": "Number of pages in the database cache",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ds_bdb_clean_pages{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Clean"
      },
      {
       "expr": "ds_bdb_dirty_pages{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Dirty"
      }
     ]
    },
    {
     "title": "DB cache pages eviction rate",
     "type": "timeseries",
     "description": "Number of cache pages evicted per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ds_bdb_page_ro_evict_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Clean"
      },
      {
       "expr": "rate(ds_bdb_page_rw_evict_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Dirty"
      }
     ]
    },
    {
     "title": "DB dirty pages trickle rate",
     "type": "timeseries",
     "description": "Average number of dirty pages written to disk per second by Berkeley DB using memp_trickle",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ds_bdb_page_trickle_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Pages"
      }
     ]
    },
    {
     "title": "Transactions rate",
     "type": "timeseries",
     "description": "Number of transactions performed by server per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ds_bdb_commit_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Committed"
      },
      {
       "expr": "rate(ds_bdb_abort_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Aborted"
      }
     ]
    },
    {
     "title": "Active transactions",
     "type": "timeseries",
     "description": "Number of transactions currently active and used by the database",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ds_bdb_active_txns{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "active"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "timeseries",
     "description": "Number of avaliable and used database locks, lock objects and lockers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ds_bdb_lockers{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Current lockers"
      },
      {
       "expr": "ds_bdb_current_locks{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Current locks"
      },
      {
       "expr": "ds_bdb_current_lock_objects{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Lock objects"
      },
      {
       "expr": "ds_bdb_configured_locks{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "Available locks"
      }
     ]
    },
    {
     "title": "Locks request rate",
     "type": "timeseries",
     "description": "Number of lock requests, lock conflicts, and deadlocks",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ds_bdb_lock_request_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Requested"
      },
      {
       "expr": "rate(ds_bdb_lock_conflicts{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Conflicts"
      },
      {
       "expr": "rate(ds_bdb_deadlock_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Deadlocks"
      }
     ]
    },
    {
     "title": "Log write rate",
     "type": "timeseries",
     "description": "Average amount of data written to the transaction log per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ds_bdb_log_write_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Written"
      }
     ]
    },
    {
     "title": "Regions wait rate",
     "type": "timeseries",
     "description": "The number of times threads were forced to wait to acquire a region lock per second, split by region type",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ds_bdb_lock_region_wait_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Lock"
      },
      {
       "expr": "rate(ds_bdb_cache_region_wait_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Cache"
      },
      {
       "expr": "rate(ds_bdb_log_region_wait_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Log"
      },
      {
       "expr": "rate(ds_bdb_txn_region_wait_rate{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Txn"
      }
     ]
    }
   ]
  },
  {
   "title": "389-ds-exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape duration",
     "type": "timeseries",
     "description": "Time of receipt of metrics by collectors",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ds_scrape_duration_seconds{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "{{collector}}"
      }
     ]
    },
    {
     "title": "Scrape success",
     "type": "timeseries",
     "description": "Success rate of collecting metrics by collectors. 1 - successful, 0 - unsuccessful",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ds_scrape_success{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "{{collector}}"
      }
     ]
    }
   ]
  }
 ]
}